version: "3.8"

services:
  web:
    build: .
    container_name: php-web
    volumes:
      - .:/var/www/html
      - ./vendor/phpmailer/phpmailer:/var/www/html/vendor/phpmailer/phpmailer
      - ./php-8.3.8:/var/www/html/php
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: mariadb-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: erik
      MYSQL_USER: erik
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
